#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: secure-user
    username: secure-user
    password: $6$Pa5Cf1I.Y/pj5nct$rXNrRLhicI9RDeAgTRBcAkIN/hrPRVuvFGy8cLNi.FO7ZR7ZiPMJ6xr7bVQIRu6.gCPF3uUxCPuhk/fisjM7w1
  locale: en_US
  keyboard:
    layout: us
    variant: ''
  storage:
    layout:
      name: lvm
    swap:
      size: 2048
    config:
      - id: disk-sda
        type: disk
        match:
          ssd: false
          size: 0
        ptable: gpt
        path: /dev/sda
        wipe: superblock
      - id: partition-boot
        type: partition
        number: 1
        size: 512M
        wipe: superblock
        flag: boot
        device: disk-sda
      - id: partition-root
        type: partition
        number: 2
        size: -1
        wipe: superblock
        flag: root
        device: disk-sda
      - id: format-boot
        type: format
        fstype: ext4
        volume: partition-boot
      - id: format-root
        type: format
        fstype: ext4
        volume: partition-root
      - id: mount-boot
        type: mount
        path: /boot
        device: format-boot
      - id: mount-root
        type: mount
        path: /
        device: format-root
  grub:
    uefi: true
  packages:
    - keepassxc
  user-data:
    late-commands:
      - |
        echo "Installing KeePassXC..."
        chroot /target apt-get update
        chroot /target apt-get -y install keepassxc

# Additional configurations can be added below

