#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - storage
    - identity
  locale: en_GB.UTF-8
  timezone: Europe/London
  keyboard:
    layout: gb
    variant: ''
  network:
    version: 2
    ethernets:
      enp6s0:
        dhcp4: true
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
      - "SHA256:o47vl96n/V33+zNV65qXrjj3MXKkcXucwXzo5Z/8ywc darkfuckerberg@meta1t0ast3r"
  swap:
    size: 2048
  packages:
    - ubuntu-desktop
    - ufw
    - fail2ban
    - apparmor
    - apparmor-profiles
    - apparmor-utils
    - cryptsetup
    - vim
    - curl
    - notesnook
    - torbrowser-launcher
    - secure-delete
    - wipe
    - kleopatra
    - keepassxc
    - openvpn
    - unattended-upgrades
    - gnupg
    - brave-browser
    - firejail
    - veracrypt
    - signal-desktop
  late-commands:
    - "echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf"
    - "echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf"
    - "echo 'net.ipv6.conf.lo.disable_ipv6 = 1' >> /etc/sysctl.conf"
    - "echo 'GRUB_CMDLINE_LINUX=\"ipv6.disable=1\"' >> /etc/default/grub"
    - "update-grub"
    - "ufw default deny incoming"
    - "ufw default allow outgoing"
    - "ufw allow from any to any port 1194 proto udp"
    - "ufw allow 22/tcp"
    - "ufw enable"
    - "fallocate -l 4G /swapfile"
    - "chmod 600 /swapfile"
    - "echo YES | cryptsetup luksFormat /swapfile"
    - "cryptsetup open /swapfile cryptswap"
    - "mkswap /dev/mapper/cryptswap"
    - "swapon /dev/mapper/cryptswap"
    - "echo '/dev/mapper/cryptswap none swap sw 0 0' >> /etc/fstab"
    - "echo '[DEFAULT]' > /etc/fail2ban/jail.local"
    - "echo 'bantime  = 10m' >> /etc/fail2ban/jail.local"
    - "echo 'findtime  = 10m' >> /etc/fail2ban/jail.local"
    - "echo 'maxretry = 5' >> /etc/fail2ban/jail.local"
    - "echo '[sshd]' >> /etc/fail2ban/jail.local"
    - "echo 'enabled = true' >> /etc/fail2ban/jail.local"
    - "echo 'port = ssh' >> /etc/fail2ban/jail.local"
    - "echo 'filter = sshd' >> /etc/fail2ban/jail.local"
    - "echo 'logpath = /var/log/auth.log' >> /etc/fail2ban/jail.local"
    - "echo 'maxretry = 3' >> /etc/fail2ban/jail.local"
    - "echo '[sshd-ddos]' >> /etc/fail2ban/jail.local"
    - "echo 'enabled = true' >> /etc/fail2ban/jail.local"
    - "echo 'port = ssh' >> /etc/fail2ban/jail.local"
    - "echo 'filter = sshd-ddos' >> /etc/fail2ban/jail.local"
    - "echo 'logpath = /var/log/auth.log' >> /etc/fail2ban/jail.local"
    - "echo 'maxretry = 2' >> /etc/fail2ban/jail.local"
    - "echo '[recidive]' >> /etc/fail2ban/jail.local"
    - "echo 'enabled = true' >> /etc/fail2ban/jail.local"
    - "echo 'logpath  = /var/log/fail2ban.log' >> /etc/fail2ban/jail.local"
    - "echo 'bantime  = 1d' >> /etc/fail2ban/jail.local"
    - "echo 'findtime  = 1d' >> /etc/fail2ban/jail.local"
    - "echo 'maxretry = 5' >> /etc/fail2ban/jail.local"
    - "echo 'action = iptables-multiport[name=recidive, port=\"ssh,smtp,imap2,imap3,pop3,pop3s\", protocol=tcp]' >> /etc/fail2ban/jail.local"
    - "systemctl restart fail2ban"
    - "echo 'Unattended-Upgrade::Allowed-Origins {\n\t\"${distro_id}:${distro_codename}-security\";\n};' > /etc/apt/apt.conf.d/50unattended-upgrades"
    - "echo 'APT::Periodic::Update-Package-Lists \"1\";' > /etc/apt/apt.conf.d/20auto-upgrades"
    - "echo 'APT::Periodic::Unattended-Upgrade \"1\";' >> /etc/apt/apt.conf.d/20auto-upgrades"
    - "echo 'APT::Periodic::AutocleanInterval \"7\";' >> /etc/apt/apt.conf.d/20auto-upgrades"
    - "echo 'APT::Periodic::Download-Upgradeable-Packages \"1\";' >> /etc/apt/apt.conf.d/20auto-upgrades"
    - "wget -q https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -O /etc/openvpn/nordvpn.zip"
    - "wget -q https://mullvad.net/download/openvpn-config/ -O /etc/openvpn/mullvad.zip"
    - "wget -q https://protonvpn.com/download/protonvpn.zip -O /etc/openvpn/protonvpn.zip"
    - "unzip /etc/openvpn/nordvpn.zip -d /etc/openvpn/nordvpn"
    - "unzip /etc/openvpn/mullvad.zip -d /etc/openvpn/mullvad"
    - "unzip /etc/openvpn/protonvpn.zip -d /etc/openvpn/protonvpn"
    - "for vpn_file in /etc/openvpn/nordvpn/*.ovpn; do nmcli con add type vpn ifname -- vpn-type openvpn con-name \"nordvpn-$(basename ${vpn_file})\" -- connection.interface-name '' vpn.data 'connection-type=password,service-type=openvpn,username=nordvpn_username,password-flags=0' vpn.secrets 'password=nordvpn_password' vpn.file \"${vpn_file}\"; done"
    - "for vpn_file in /etc/openvpn/mullvad/*.ovpn; do nmcli con add type vpn ifname -- vpn-type openvpn con-name \"mullvad-$(basename ${vpn_file})\" -- connection.interface-name '' vpn.data 'connection-type=password,service-type=openvpn,username=mullvad_username,password-flags=0' vpn.secrets 'password=mullvad_password' vpn.file \"${vpn_file}\"; done"
    - "for vpn_file in /etc/openvpn/protonvpn/*.ovpn; do nmcli con add type vpn ifname -- vpn-type openvpn con-name \"protonvpn-$(basename ${vpn_file})\" -- connection.interface-name '' vpn.data 'connection-type=password,service-type=openvpn,username=protonvpn_username,password-flags=0' vpn.secrets 'password=protonvpn_password' vpn.file \"${vpn_file}\"; done"
    - "echo '#!/bin/bash' > /etc/network/if-pre-up.d/random-vpn"
    - "echo 'VPN_FILES=(/etc/openvpn/nordvpn/*.ovpn /etc/openvpn/mullvad/*.ovpn /etc/openvpn/protonvpn/*.ovpn)' >> /etc/network/if-pre-up.d/random-vpn"
    - "echo 'RANDOM_VPN_FILE=${VPN_FILES[$RANDOM % ${#VPN_FILES[@]}]}' >> /etc/network/if-pre-up.d/random-vpn"
    - "echo 'nmcli con up \"${RANDOM_VPN_FILE}\"' >> /etc/network/if-pre-up.d/random-vpn"
    - "chmod +x /etc/network/if-pre-up.d/random-vpn"
    - "echo 'net.ipv4.conf.all.rp_filter=1' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.conf.default.rp_filter=1' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.tcp_syncookies=1' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.conf.all.accept_redirects=0' >> /etc/sysctl.conf"
    - "echo 'net.ipv6.conf.all.accept_redirects=0' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.conf.all.secure_redirects=0' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.icmp_echo_ignore_broadcasts=1' >> /etc/sysctl.conf"
    - "echo 'net.ipv4.icmp_ignore_bogus_error_responses=1' >> /etc/sysctl.conf"
    - "echo 'kernel.randomize_va_space=2' >> /etc/sysctl.conf"
    - "aa-enforce /etc/apparmor.d/*"
    - "sed -i '/defaults/ s/defaults/defaults,noatime,nodiratime,commit=120/' /etc/fstab"
    - "echo 'vm.swappiness=10' >> /etc/sysctl.conf"
    - "echo 'vm.dirty_ratio=20' >> /etc/sysctl.conf"
    - "echo 'vm.dirty_background_ratio=5' >> /etc/sysctl.conf"
    - "add-apt-repository -y ppa:unit193/encryption"
    - "apt-get update"
    - "apt-get install -y veracrypt"
    - "wget -O- https://updates.signal.org/desktop/apt/keys.asc | apt-key add -"
    - "echo 'deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main' | tee -a /etc/apt/sources.list.d/signal-xenial.list"
    - "apt-get update"
    - "apt-get install -y signal-desktop"

